chore(root): add commit lint #1

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,4 +1,7 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-dart run commitlint_cli --edit ${1}
+dart run commitlint_cli --edit ${1} || {
+  echo "Commit lint failed. Trying run on fvm..."
+  fvm dart run commitlint_cli --edit ${1}
+}
diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,7 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-flutter analyze
+flutter analyze || {
+  echo "Flutter analyze failed. Trying run on fvm..."
+  fvm flutter analyze
+}
